backend:
  name: github
  repo: clairezed/LGML_docs # Path to your Github repository
  branch: master # Branch to update

# # interface for drafting, reviewing, and approving posts.
# publish_mode: editorial_workflow

media_folder: "docs/assets/img"
public_folder: "/docs/assets/img"

collections:
  - name: "blog" # Used in routes, e.g. /admin/collections/blog
    label: "Articles" # Used in the UI
    folder: "docs/_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Date de publication", name: "date", widget: "datetime"}
      - {label: "Categories", name: "categories", widget: "list"}
      - {label: "Contenu", name: "body", widget: "markdown"}
      # - {label: "Featured Image", name: "image", widget: "image"}
      # - {label: "Rating (scale of 1-5)", name: "rating", widget: "number"}
  - name: "about" # Used in routes, e.g. /admin/collections/blog
    label: "A propos" # Used in the UI
    folder: "docs/_docs/about" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{permalink}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Categorie", name: "category", widget: "string"}
      - {label: "Position", name: "order", widget: "number"}
      - {label: "Contenu", name: "body", widget: "markdown"}
  - name: "features" # Used in routes, e.g. /admin/collections/blog
    label: "Fonctionnalités" # Used in the UI
    folder: "docs/_docs/features" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{permalink}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Categorie", name: "category", widget: "string"}
      - {label: "Position", name: "order", widget: "number"}
      - {label: "Contenu", name: "body", widget: "markdown"}
  - name: "interface" # Used in routes, e.g. /admin/collections/blog
    label: "Fonctionnalités" # Used in the UI
    folder: "docs/_docs/interface" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{permalink}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Categorie", name: "category", widget: "string"}
      - {label: "Position", name: "order", widget: "number"}
      - {label: "Contenu", name: "body", widget: "markdown"}
      - {label: "Image", name: "image", widget: "image"}
